=== dabiboo/habitv/trunk/application/core/xsd/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.dabi.com/habitv/configuration/entities"
	targetNamespace="http://www.dabi.com/habitv/configuration/entities">
	<element name="configuration">
		<complexType>
			<all>
				<element name="proxies" minOccurs="0">
					<complexType>
						<sequence>
							<element name="proxy" type="tns:Proxy" maxOccurs="unbounded"
								minOccurs="0" />
						</sequence>
					</complexType>
				</element>
				<element name="osConfig" minOccurs="0">
					<complexType>
						<all>
							<element name="cmdProcessor" type="string" maxOccurs="1"
								minOccurs="0" />
						</all>
					</complexType>
				</element>
				<element name="downloadConfig" minOccurs="0">
					<complexType>
						<all>
							<element name="downloadOuput" type="string" minOccurs="0" />
							<element name="maxAttempts" type="int" minOccurs="0" />
							<element name="demonCheckTime" type="int" minOccurs="0" />
							<element name="fileNameCutSize" type="int" minOccurs="0" />
							<element name="downloaders" maxOccurs="1" minOccurs="0">
								<complexType>
									<sequence>
										<any minOccurs="0" maxOccurs="unbounded" namespace="##any"
											processContents="lax" />
									</sequence>
								</complexType>
							</element>
						</all>
					</complexType>
				</element>
				<element name="dirConfig" minOccurs="0">
					<complexType>
						<all>
							<element name="indexDir" type="string" minOccurs="0"/>
							<element name="pluginDir" type="string" minOccurs="0"/>
							<element name="binDir" type="string" minOccurs="0"/>
						</all>
					</complexType>
				</element>
				<element name="updateConfig" minOccurs="0">
					<complexType>
						<all>
							<element name="updateOnStartup" type="boolean" minOccurs="0" />
							<element name="autoriseSnapshot" type="boolean"
								minOccurs="0" />
						</all>
					</complexType>
				</element>
				<element name="exportConfig" minOccurs="0">
					<complexType>
						<all>
							<element name="exporters" maxOccurs="1" minOccurs="0">
								<complexType>
									<sequence>
										<element name="exporter" type="tns:exporter"
											maxOccurs="unbounded" minOccurs="0" />
									</sequence>
								</complexType>
							</element>
						</all>
					</complexType>
				</element>
				<element name="taskDefinition" minOccurs="0">
					<complexType>
						<sequence>
							<any minOccurs="0" maxOccurs="unbounded" namespace="##any"
								processContents="lax" />
						</sequence>
					</complexType>
				</element>
			</all>
		</complexType>
	</element>

	<complexType name="exporter">
		<all>
			<element name="condition" type="tns:conditionType" minOccurs="0" />
			<element name="id" type="string" />
			<element name="label" type="string" />
			<element name="command" type="string" />
			<element name="subexporters">
				<complexType>
					<sequence>
						<element name="exporter" type="tns:exporter" maxOccurs="unbounded"
							minOccurs="0">
						</element>
					</sequence>
				</complexType>
			</element>
		</all>
	</complexType>

	<complexType name="conditionType">
		<all>
			<element name="reference" type="string" />
			<element name="pattern" type="string" />
		</all>
	</complexType>

	<complexType name="Proxy">
		<all>
			<element name="protocol" type="string" />
			<element name="host" type="string" />
			<element name="port" type="int" />
			<element name="pluginSupport" type="tns:pluginSupport"/>
		</all>
	</complexType>

	<complexType name="pluginSupport">
		<sequence>
			<element name="plugin" type="string" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
	</complexType>
</schema>

=== dabiboo/habitv/tags/application-4.0.6/core/xsd/configuration-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:configuration xmlns:tns="http://www.dabi.com/habitv/configuration/entities" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dabi.com/habitv/configuration/entities configuration.xsd ">
  <proxies>
    <proxy>
      <protocol>protocol</protocol>
      <host>host</host>
      <port>0</port>
      <pluginSupport>
        <plugin>plugin</plugin>
      </pluginSupport>
    </proxy>
  </proxies>
  <osConfig>
    <cmdProcessor>cmdProcessor</cmdProcessor>
  </osConfig>
  <downloadConfig>
    <downloadOuput>downloadOuput</downloadOuput>
    <maxAttempts>0</maxAttempts>
    <demonCheckTime>0</demonCheckTime>
    <fileNameCutSize>0</fileNameCutSize>
    <downloaders/>
  </downloadConfig>
  <updateConfig>
    <updateOnStartup>true</updateOnStartup>
    <autoriseSnapshot>true</autoriseSnapshot>
  </updateConfig>
  <exportConfig>
    <exporters>
      <exporter>
        <condition>
          <reference>reference</reference>
          <pattern>pattern</pattern>
        </condition>
        <id>id</id>
        <label>label</label>
        <command>command</command>
        <subexporters/>
      </exporter>
    </exporters>
  </exportConfig>
  <taskDefinition/>
</tns:configuration>
