=== dabiboo/habitv/trunk/application/core/xsd/grab-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.dabi.com/habitv/grabconfig/entities"
	targetNamespace="http://www.dabi.com/habitv/grabconfig/entities">


	<element name="grabConfig">
		<complexType>
			<sequence>
				<element name="channels" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<element name="channel" type="tns:channelType" maxOccurs="unbounded"
								minOccurs="0"></element>
						</sequence>
					</complexType>
				</element>
				<element name="channel" type="tns:channel" maxOccurs="unbounded"
					minOccurs="0"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="category">
		<sequence>
			<element name="id" type="string"></element>
			<element name="name" type="string"></element>
			<element name="toDownload" type="boolean" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="include" type="string" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="exclude" type="string" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="category" type="tns:category" maxOccurs="unbounded"
				minOccurs="0">
			</element>
			<element name="extension" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="status" type="string" maxOccurs="1" minOccurs="0">
			</element>
			<element name="parameter" type="tns:parameter" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="categoryType">
		<all>
			<element name="id" type="string" />
			<element name="name" type="string" />
			<element name="download" type="boolean" minOccurs="0"/>
			<element name="includes" minOccurs="0">
				<complexType>
					<sequence>
						<element name="include" type="string" maxOccurs="unbounded"
							minOccurs="0" />
					</sequence>
				</complexType>
			</element>
			<element name="excludes" minOccurs="0">
				<complexType>
					<sequence>
						<element name="exclude" type="string" maxOccurs="unbounded"
							minOccurs="0" />
					</sequence>
				</complexType>
			</element>
			<element name="subcategories" minOccurs="0">
				<complexType>
					<sequence>
						<element name="category" type="tns:categoryType"
							minOccurs="0" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
			<element name="extension" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="status" type="string" minOccurs="0"/>
			<element name="configuration" minOccurs="0">
				<complexType>
					<sequence>
						<any minOccurs="0" maxOccurs="unbounded" namespace="##any" processContents="lax" />
					</sequence>
				</complexType>
			</element>
		</all>
	</complexType>

	<complexType name="channelType">
		<all>
			<element name="name" type="string" />
			<element name="categories">
				<complexType>
					<sequence>
						<element name="category" type="tns:categoryType"
							minOccurs="0" maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
			<element name="status" type="int" />
		</all>
	</complexType>

	<complexType name="channel">
		<sequence>
			<element name="name" type="string"></element>
			<element name="category" type="tns:category" maxOccurs="unbounded"
				minOccurs="1">
			</element>
			<element name="status" type="int" maxOccurs="1" minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="parameter">
		<sequence>
			<element name="key" type="string"></element>
			<element name="value" type="string"></element>
		</sequence>
	</complexType>
</schema>

=== dabiboo/habitv/tags/parent-4.0.3/application/core/xsd/grab-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:grabConfig xmlns:tns="http://www.dabi.com/habitv/grabconfig/entities" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dabi.com/habitv/grabconfig/entities grab-config.xsd ">
  <plugins>
    <plugin>
      <name>name</name>
      <categories>
        <category>
          <id>id</id>
          <name>name</name>
        </category>
      </categories>
      <status>status</status>
      <deleted>true</deleted>
    </plugin>
  </plugins>
  <channel>
    <name>name</name>
    <category>
      <id>id</id>
      <name>name</name>
      <toDownload>true</toDownload>
      <include>include</include>
      <exclude>exclude</exclude>
      <category/>
      <extension>extension</extension>
      <status>0</status>
      <parameter>
        <key>key</key>
        <value>value</value>
      </parameter>
    </category>
    <status>status</status>
  </channel>
</tns:grabConfig>

=== dabiboo/habitv/trunk/habiTv/grabconfig.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tns:grabConfig xmlns:tns="http://www.dabi.com/habitv/grabconfig/entities"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dabi.com/habitv/grabconfig/entities grab-config.xsd ">
	<!-- <channel> <name>m6</name> <category> <id>3538</id> <name>Scènes de 
		ménages </name> <include>.*20h.*</include> <exclude>.*13h00.*</exclude> </category> 
		<category> <id>6026</id> <name>Un gars, une fille</name> </category> <category> 
		<id>2276</id> <name>Cinésix</name> </category> <category> <id>116</id> <name>66 
		Minutes</name> </category> </channel> -->
	<!-- <channel> <name>tvSubtitles</name> <category> <id>tvshow-911-2.html</id> 
		<name>Game of Thrones</name> <extension>zip</extension> </category> <category> 
		<id>tvshow-967-1.html</id> <name>Revenge</name> <extension>zip</extension> 
		</category> <category> <id>tvshow-679-1.html</id> <name>Awake</name> <extension>zip</extension> 
		</category> <category> <id>tvshow-1104-1.html</id> <name>The Client List</name> 
		<extension>zip</extension> </category> </channel> -->
	<channel>
		<name>canalPlus</name>
		<!-- <category>
			<id>634012</id>
			<name>LES GUIGNOLS</name>
			<exclude>.*La semaine des Guignols.*</exclude>
			<extension>mp4</extension>
		</category>
		<category>
			<id>619685</id>
			<name>LE JT DE CANAL+</name>
			<extension>mp4</extension>
		</category>
		<category>
			<id>633988</id>
			<name>BREF</name>
			<extension>mp4</extension>
		</category>
		<category>
			<id>633844</id>
			<name>ZAPPING</name>
			<extension>mp4</extension>
		</category> -->
		<category>
			<id>3</id>
			<name>TOUT LE FOOTBALL</name>
			<include>.*Multiplex.*</include>
			<include>.*Sporting.*</include>
			<include>.*Atletico Madrid.*</include>
			<include>.*Real Madrid.*</include>
			<include>.*Barcelone.*</include>
			<include>.*Valence.*</include>
			<include>.*Bilbao.*</include>
			<include>.*Inter Milan.*</include>
			<include>.*AC Milan.*</include>
			<include>.*AS Roma.*</include>
			<include>.*Juventus Turin.*</include>
			<include>.*Newcastle United.*</include>
			<include>.*Arsenal.*</include>
			<include>.*Chelsea.*</include>
			<include>.*Tottenham.*</include>
			<include>.*Manchester United.*</include>
			<include>.*Manchester City.*</include>
			<include>.*Top buts.*</include>
			<include>.*Les 5 plus beaux buts.*</include>
			<include>.*Marseille.*</include>
			<include>.*Bayern Munich.*</include>
			<include>.*USA.*</include>
			<include>.*Ecosse.*</include>
			<include>.*Angleterre.*</include>
			<include>.*Norvège.*</include>
			<include>.*Espagne.*</include>
			<include>.*Serbie.*</include>
			<include>.*Suisse.*</include>
			<include>.*Allemagne.*</include>
			<include>.*Danemark.*</include>
			<include>.*Brésil.*</include>
			<include>.*France.*</include>
			<include>.*Italie.*</include>
			<exclude>.*LE MEILLEUR DU CFC.*</exclude>
			<exclude>.*The Specialists.*</exclude>
			<extension>mp4</extension>
		</category>
		<!-- <category>
			<id>47</id>
			<name>LES EXCLUS DU WEB </name>
			<category>
				<id>631443</id>
				<name>PEPITES SUR LE NET</name>
				<extension>mp4</extension>
			</category>
			<extension>mp4</extension>
		</category>
		<category>
			<id>73</id>
			<name>LES PLUS RECENTES</name>
			<category>
				<id>634058</id>
				<name>ZAPSPORT</name>
				<extension>mp4</extension>
			</category>
			<extension>mp4</extension>
		</category>
		 -->
	</channel>
	<!-- <channel> <name>soirFoot</name> <category> <id>browse-Ligue-1-Ligue1-videos-1-date.html</id> 
		<name>Ligue 1</name> </category> </channel> -->
	<!-- <channel>
		<name>rss</name>
		<category>
			<id>http://ezrss.it/search/index.php?show_name=how+i+met+your+mother&amp;date=&amp;quality=&amp;release_group=&amp;mode=rss
			</id>
			<name>How I Met Your Mother</name>
			<extension>torrent</extension>
		</category>
	</channel>
	 -->
</tns:grabConfig>
