=== dabiboo/habitv/1.0.x/current/habiTv/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.dabi.com/habitv/config/entities"
	targetNamespace="http://www.dabi.com/habitv/config/entities">
	<complexType name="config">
		<sequence>
			<element name="demonTime" type="int" maxOccurs="1"
				minOccurs="0" />
			<element name="workingDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="indexDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="providerPluginDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="downloaderPluginDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="exporterPluginDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="downloadOuput" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="downloader" type="tns:downloader" maxOccurs="unbounded"
				minOccurs="1">
			</element>
			<element name="exporter" type="tns:exporter" maxOccurs="unbounded"
				minOccurs="0" />
			<element name="simultaneousChannelDownload" type="int"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="simultaneousEpisodeDownload" type="int"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="simultaneousExport" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="allDownloadTimeout" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="exportTimeout" type="int" maxOccurs="1"
				minOccurs="1">
			</element>

		</sequence>
	</complexType>

	<element name="config" type="tns:config"></element>

	<complexType name="downloader">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="binPath" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="exporter">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="output" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="cmd" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="exporter" type="tns:exporter" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
	</complexType>
</schema>

=== dabiboo/habitv/branches/1.0.x/habiTv/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
  <!-- <demonTime>10</demonTime> -->
  <workingDir>../builder/pub</workingDir>
  <indexDir>../builder/pub/index</indexDir>
  <providerPluginDir>../builder/pub/provider</providerPluginDir>
  <downloaderPluginDir>../builder/pub/downloader</downloaderPluginDir>
  <exporterPluginDir>../builder/pub/exporter</exporterPluginDir> 
  <downloadOuput>D:/divx/regular/#EPISODE_NAME_NOSCORE#.mp4</downloadOuput>
  <downloader>
    <name>http</name>
    <cmd></cmd>
  </downloader>  
  <downloader>
    <name>rtmpdump</name>
    <cmd>D:\script\habiTv\bin\rtmpdump.exe</cmd>
  </downloader>
  <downloader>
    <name>curl</name>
    <cmd>D:\script\habiTv\bin\curl\curl.exe</cmd>
  </downloader>  
  <exporter>
    <name>ffmpeg</name>
    <output>Re-encoding</output>
    <cmd>ffmpeg -y -i "D:\divx\regular\#EPISODE_NAME_NOSCORE#.mp4" -vtag DIVX -f avi -vcodec mpeg4 -b 2600000 -acodec mp2 -ab 192000 -ar 48000 -ac 2  "D:\divx\regular\#EPISODE_NAME_NOSCORE#.avi"</cmd>
  </exporter>
  <exporter>
    <name>move</name>
    <output>moving</output>
    <cmd>cmd /c move /Y D:\divx\regular\#EPISODE_NAME_NOSCORE#.avi D:\divx\regular\avi</cmd>
  	<exporter>
    	<name>ftp</name>
    	<output>Transferring to freebox</output>
    	<cmd>D:\script\ftp\uploadToFtp.bat #TVSHOW_NAME# D:\divx\regular\avi\#EPISODE_NAME_NOSCORE#.avi</cmd>
  	</exporter>   
  	<exporter>
    	<name>del</name>
    	<output>Deleting</output>
    	<cmd>cmd /c del D:\divx\regular\#EPISODE_NAME_NOSCORE#.mp4</cmd>
  	</exporter>    
  </exporter>    
  <simultaneousChannelDownload>3</simultaneousChannelDownload>
  <simultaneousEpisodeDownload>2</simultaneousEpisodeDownload>
  <simultaneousExport>1</simultaneousExport>
  <timeBetweenLog>3</timeBetweenLog>
  <allDownloadTimeout>3600</allDownloadTimeout>
  <exportTimeout>3600</exportTimeout>
</tns:config>

=== dabiboo/habitv/2.0.x/2.0.0/habiTv/configKlaus.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
  <!-- <demonTime>10</demonTime> -->
  <workingDir>../builder/pub</workingDir>
  <indexDir>../builder/pub/index</indexDir>
  <providerPluginDir>../builder/pub/provider</providerPluginDir>
  <downloaderPluginDir>../builder/pub/downloader</downloaderPluginDir>
  <exporterPluginDir>../builder/pub/exporter</exporterPluginDir> 
  <downloadOuput>D:/divx/regular/#EPISODE_NAME_CUT#.mp4</downloadOuput>
  <downloader>
    <name>http</name>
  </downloader>  
  <downloader>
    <name>rtmpdump</name>
    <binPath>..\rtmpDumpDownloader\exe\rtmpdump.exe</binPath>
  </downloader>
  <downloader>
    <name>aria2</name>
    <binPath>..\aria2Downloader\exe\aria2c.exe</binPath>
  </downloader>  
  <downloader>
    <name>curl</name>
    <binPath>..\curlDownloader\exe\curl.exe</binPath>
  </downloader>  
  <exporter>
    <name>ffmpeg</name>
    <output>Re-encoding</output>
    <cmd>../ffmpegExporter/exe/ffmpeg.exe -y -i "D:\divx\regular\#EPISODE_NAME_CUT#.mp4" -vtag DIVX -f avi -vcodec mpeg4 -b 2600000 -acodec mp2 -ab 192000 -ar 48000 -ac 2  "D:\divx\regular\#EPISODE_NAME_CUT#.avi"</cmd>
  </exporter>
  <exporter>
    <name>move</name>
    <output>moving</output>
    <cmd>cmd /c move /Y D:\divx\regular\#EPISODE_NAME_CUT#.avi D:\divx\regular\avi</cmd>
  	<exporter>
    	<name>ftp</name>
    	<output>Transferring to freebox</output>
    	<cmd>D:\script\ftp\uploadToFtp.bat #TVSHOW_NAME# D:\divx\regular\avi\#EPISODE_NAME_CUT#.avi</cmd>
  	</exporter>   
  	<exporter>
    	<name>del</name>
    	<output>Deleting</output>
    	<cmd>cmd /c del D:\divx\regular\#EPISODE_NAME_NOSCORE#.mp4</cmd>
  	</exporter>    
  </exporter>    
  <simultaneousChannelDownload>3</simultaneousChannelDownload>
  <simultaneousEpisodeDownload>2</simultaneousEpisodeDownload>
  <simultaneousExport>1</simultaneousExport>
  <allDownloadTimeout>3600</allDownloadTimeout>
  <exportTimeout>3600</exportTimeout>
</tns:config>

=== dabiboo/habitv/trunk/builder/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
  <demonTime>1800</demonTime>
  <workingDir>.</workingDir>
  <indexDir>index</indexDir>
  <providerPluginDir>provider</providerPluginDir>
  <downloaderPluginDir>downloader</downloaderPluginDir>
  <exporterPluginDir>exporter</exporterPluginDir> 
  <downloadOuput>#TVSHOW_NAME#_#EPISODE_NAME_CUT#.mp4</downloadOuput>
  <downloader>
    <name>rtmpdump</name>
    <binPath>bin\rtmpdump.exe</binPath>
  </downloader>
  <downloader>
    <name>curl</name>
    <binPath>bin\curl.exe</binPath>
  </downloader>
  <downloader>
    <name>aria2</name>
    <binPath>bin\aria2c.exe</binPath>
  </downloader>   
  <simultaneousChannelDownload>3</simultaneousChannelDownload>
  <simultaneousEpisodeDownload>2</simultaneousEpisodeDownload>
  <simultaneousExport>1</simultaneousExport>
  <allDownloadTimeout>7200</allDownloadTimeout>
  <exportTimeout>7200</exportTimeout>
</tns:config>
