=== dabiboo/habitv/tags/parent-4.0.1/application/core/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.dabi.com/habitv/config/entities"
	targetNamespace="http://www.dabi.com/habitv/config/entities">
	<complexType name="config">
		<sequence>
			<element name="proxy" type="tns:Proxy" maxOccurs="unbounded"
				minOccurs="0"></element>
			<element name="maxAttempts" type="int" maxOccurs="1"
				minOccurs="0" />
			<element name="cmdProcessor" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="demonTime" type="int" maxOccurs="1"
				minOccurs="0" />
			<element name="fileNameCutSize" type="int" maxOccurs="1"
				minOccurs="0" />
			<element name="workingDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="indexDir" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="providerPluginDir" type="string"
				maxOccurs="1" minOccurs="1" />
			<element name="downloaderPluginDir" type="string"
				maxOccurs="1" minOccurs="1" />
			<element name="exporterPluginDir" type="string"
				maxOccurs="1" minOccurs="1" />
			<element name="downloadOuput" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="downloader" type="tns:downloader"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="exporter" type="tns:exporter"
				maxOccurs="unbounded" minOccurs="0" />
			<element name="taskDefinition" type="tns:taskDefinition"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<element name="config" type="tns:config"></element>

	<complexType name="downloader">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="binPath" type="string" maxOccurs="1"
				minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="exporter">
		<sequence>
			<element name="condition" type="tns:conditionType" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="name" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="output" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="cmd" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="exporter" type="tns:exporter" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="conditionType">
		<sequence>
			<element name="reference" type="string"></element>
			<element name="pattern" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="taskDefinition">
		<sequence>
			<element name="taskName" type="string"></element>
			<element name="size" type="int"></element>
		</sequence>
	</complexType>

	<complexType name="Proxy">
		<sequence>
			<element name="protocol" type="string"></element>
			<element name="host" type="string"></element>
			<element name="port" type="int"></element>
			<element name="pluginSupport" type="tns:pluginSupport" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="pluginSupport">
		<sequence>
			<element name="plugin" type="string" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>
</schema>

=== dabiboo/habitv/trunk/habiTv/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
	<!-- <demonTime>10</demonTime> -->
	<workingDir>../builder/pub</workingDir>
	<indexDir>C:/Program Files (x86)/habiTv/index</indexDir>
	<providerPluginDir>../builder/pub/provider</providerPluginDir>
	<downloaderPluginDir>../builder/pub/downloader</downloaderPluginDir>
	<exporterPluginDir>../builder/pub/exporter</exporterPluginDir>
	<downloadOuput>D:/divx/regular/#EPISODE_NAME_CUT#.#EXTENSION#</downloadOuput>
	<downloader>
		<name>http</name>
	</downloader>
	<downloader>
		<name>rtmpdump</name>
		<binPath>..\rtmpDumpDownloader\exe\rtmpdump.exe</binPath>
	</downloader>
	<downloader>
		<name>aria2</name>
		<binPath>..\aria2Downloader\exe\aria2c.exe</binPath>
	</downloader>
	<downloader>
		<name>curl</name>
		<binPath>..\curlDownloader\exe\curl.exe</binPath>
	</downloader>
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>ffmpeg</name>
		<output>Re-encoding</output>
		<cmd>../ffmpegExporter/exe/ffmpeg.exe -y -i
			"D:\divx\regular\#EPISODE_NAME_CUT#.#EXTENSION#" -vtag DIVX -f avi
			-vcodec mpeg4 -b 2600000 -acodec mp2 -ab 192000 -ar 48000 -ac 2
			"D:\divx\regular\#EPISODE_NAME_CUT#.avi"
		</cmd>
	</exporter>
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>move</name>
		<output>moving</output>
		<cmd>cmd /c move /Y D:\divx\regular\#EPISODE_NAME_CUT#.avi
			D:\divx\regular\avi\
		</cmd>
		<exporter>
			<condition>
				<reference>#EXTENSION#</reference>
				<pattern>mp4|flv</pattern>
			</condition>
			<name>curl</name>
			<output>Transferring to freebox</output>
			<cmd>..\curlDownloader\exe\curl.exe -T
				"D:/divx/regular/avi/#EPISODE_NAME_CUT#.avi"
				"ftp://freebox:4688@hd1.freebox.fr/Disque dur/#TVSHOW_NAME#/"
				--ftp-create-dirs
			</cmd>
		</exporter>
		<exporter>
			<name>del</name>
			<output>Deleting</output>
			<cmd>cmd /c del D:\divx\regular\#EPISODE_NAME_NOSCORE#.#EXTENSION#
			</cmd>
		</exporter>
	</exporter>
	<allDownloadTimeout>3600</allDownloadTimeout>
	<exportTimeout>3600</exportTimeout>
	<simultaneousTaskNumber>
		<taskName>export</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>export_main</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>search</taskName>
		<size>5</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>download</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>curl</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
</tns:config>

=== dabiboo/habitv/branches/3.2.x/current/builder/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
	<demonTime>1800</demonTime>
	<workingDir>pub</workingDir>
	<indexDir>index</indexDir>
	<providerPluginDir>provider</providerPluginDir>
	<downloaderPluginDir>downloader</downloaderPluginDir>
	<exporterPluginDir>exporter</exporterPluginDir>
	<downloadOuput>downloads/#TVSHOW_NAME#-#EPISODE_NAME_CUT#.#EXTENSION#</downloadOuput>
	<downloader>
		<name>http</name>
	</downloader>
	<downloader>
		<name>rtmpdump</name>
		<binPath>bin\rtmpdump.exe</binPath>
	</downloader>
	<downloader>
		<name>aria2</name>
		<binPath>bin\aria2c.exe</binPath>
	</downloader>
	<downloader>
		<name>curl</name>
		<binPath>bin\curl.exe</binPath>
	</downloader>
	<taskDefinition>
		<taskName>category</taskName>
		<size>5</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>export</taskName>
		<size>2</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>retreive</taskName>
		<size>50</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>search</taskName>
		<size>5</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>download</taskName>
		<size>2</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>curl</taskName>
		<size>2</size>		
	</taskDefinition>
	<taskDefinition>
		<taskName>ffmpeg</taskName>
		<size>1</size>
	</taskDefinition>	
</tns:config>

=== dabiboo/habitv/trunk/trayView/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
	<proxy>
		<protocol>HTTP</protocol>
		<host>127.0.0.1</host>
		<port>6588</port>
	</proxy>
	<proxy>
		<protocol>SOCKS</protocol>
		<host>127.0.0.1</host>
		<port>1080</port>
	</proxy>	
	<maxAttempts>1</maxAttempts>
	<demonTime>1800</demonTime>
	<fileNameCutSize>50</fileNameCutSize>
	<workingDir>../builder/pub</workingDir>
	<indexDir>../builder/pub/index</indexDir>
	<providerPluginDir>../builder/pub/provider</providerPluginDir>
	<downloaderPluginDir>../builder/pub/downloader</downloaderPluginDir>
	<exporterPluginDir>../builder/pub/exporter</exporterPluginDir>
	<downloadOuput>../builder/pub/downloads/#TVSHOW_NAME#-#EPISODE_NAME_CUT#.#EXTENSION#</downloadOuput>
	<downloader>
		<name>http</name>
	</downloader>
	<downloader>
		<name>rtmpdump</name>
		<binPath>..\rtmpDumpDownloader\exe\rtmpdump.exe</binPath>
	</downloader>
	<downloader>
		<name>aria2</name>
		<binPath>..\aria2Downloader\exe\aria2c.exe</binPath>
	</downloader>
	<downloader>
		<name>curl</name>
		<binPath>..\curlDownloader\exe\curl.exe</binPath>
	</downloader>
	<downloader>
		<name>ffmpeg</name>
		<binPath>..\ffmpegExporter\exe\ffmpeg.exe</binPath>
	</downloader>
	<downloader>
		<name>youtube</name>
		<binPath>..\youtubeDownloader\exe\youtube-dl.exe</binPath>
	</downloader>
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>ffmpeg</name>
		<output>Re-encoding</output>
		<cmd>D:\script\video\gen\convertAviMp2Auto.bat "../builder/pub/downloads/#TVSHOW_NAME#-#EPISODE_NAME_CUT#.#EXTENSION#" "D:\divx\regular\#TVSHOW_NAME#-#EPISODE_NAME_CUT#.avi"</cmd>
	</exporter>
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>move</name>
		<output>moving</output>
		<cmd>cmd /c move /Y D:\divx\regular\#TVSHOW_NAME#-#EPISODE_NAME_CUT#.avi D:\divx\regular\avi\</cmd>
	</exporter>
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>curl</name>
		<output>Transferring to freebox</output>
		<cmd>..\curlDownloader\exe\curl.exe -T "D:/divx/regular/avi/#TVSHOW_NAME#-#EPISODE_NAME_CUT#.avi" "ftp://freebox:4688@hd1.freebox.fr/Disque dur/#TVSHOW_NAME#/#EPISODE_NAME_CUT#.avi" --ftp-create-dirs</cmd>
	</exporter>
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>del</name>
		<output>Deleting</output>
		<cmd>cmd /c del ..\builder\pub\downloads\#TVSHOW_NAME#-#EPISODE_NAME_CUT#.#EXTENSION#</cmd>		
	</exporter>
	<exporter>
		<condition>
			<reference>#CHANNEL_NAME#</reference>
			<pattern>tvSubtitles</pattern>
		</condition>
		<name>mkv</name>
		<output>merge subtitle to video</output>
		<cmd>D:\script\closer\closer.bat "..\builder\pub\downloads\#TVSHOW_NAME#-#EPISODE_NAME_CUT#.#EXTENSION#" "D:\divx\regular\#TVSHOW_NAME#-#EPISODE_NAME_CUT#.mkv"</cmd>
	</exporter>
	<exporter>
		<condition>
			<reference>#CHANNEL_NAME#</reference>
			<pattern>tvSubtitles</pattern>
		</condition>
		<name>curl</name>
		<output>Transferring to freebox</output>
		<cmd>..\curlDownloader\exe\curl.exe -T "D:/divx/regular/#TVSHOW_NAME#-#EPISODE_NAME_CUT#.mkv" "ftp://freebox:4688@hd1.freebox.fr/Disque	dur/#TVSHOW_NAME#/#EPISODE_NAME_CUT#.avi" --ftp-create-dirs</cmd>
	</exporter>	
	<taskDefinition>
		<taskName>category</taskName>
		<size>5</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>export</taskName>
		<size>2</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>retreive</taskName>
		<size>50</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>search</taskName>
		<size>5</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>download</taskName>
		<size>2</size>
	</taskDefinition>
	<taskDefinition>
		<taskName>curl</taskName>
		<size>2</size>		
	</taskDefinition>
	<taskDefinition>
		<taskName>ffmpeg</taskName>
		<size>1</size>
	</taskDefinition>
</tns:config>

=== dabiboo/habitv/2.1.x/2.1.0/builder/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.dabi.com/habitv/config/entities"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dabi.com/habitv/config/entities config.xsd ">
  <demonTime>1800</demonTime>
  <workingDir>.</workingDir>
  <indexDir>index</indexDir>
  <providerPluginDir>provider</providerPluginDir>
  <downloaderPluginDir>downloader</downloaderPluginDir>
  <exporterPluginDir>exporter</exporterPluginDir> 
  <downloadOuput>downloads/#TVSHOW_NAME#_#EPISODE_NAME_CUT#.#EXTENSION#</downloadOuput>
	<downloader>
		<name>http</name>
	</downloader>
	<downloader>
		<name>rtmpdump</name>
		<binPath>bin\rtmpdump.exe</binPath>
	</downloader>
	<downloader>
		<name>aria2</name>
		<binPath>bin\aria2c.exe</binPath>
	</downloader>
	<downloader>
		<name>curl</name>
		<binPath>bin\curl.exe</binPath>
	</downloader>
  	<!--<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>	
    	<name>mkdir</name>
    	<output>Create dir</output>
    	<cmd>cmd /c mkdir "D:\divx\regular\avi\#TVSHOW_NAME#" | echo createdir</cmd>
  	</exporter>	
	<exporter>
		<condition>
			<reference>#EXTENSION#</reference>
			<pattern>mp4|flv</pattern>
		</condition>
		<name>ffmpeg</name>
		<output>Re-encoding</output>
		<cmd>bin/ffmpeg.exe -y -i
			"D:\divx\regular\#TVSHOW_NAME#_#EPISODE_NAME_CUT#.#EXTENSION#" -vtag DIVX -f avi
			-vcodec mpeg4 -b 2600000 -acodec mp2 -ab 192000 -ar 48000 -ac 2
			"D:\divx\regular\avi\#TVSHOW_NAME#\#EPISODE_NAME_CUT#.avi"
		</cmd>
		<exporter>
			<condition>
				<reference>#EXTENSION#</reference>
				<pattern>mp4|flv</pattern>
			</condition>
			<name>ftp</name>
			<output>Transferring to freebox</output>
			<cmd>bin\curl.exe -T "D:\divx\regular\avi\#TVSHOW_NAME#\#EPISODE_NAME_CUT#.avi" "ftp://freebox:4688@hd1.freebox.fr/Disque dur/#TVSHOW_NAME#/" -REMOVEME-ftp-create-dirs</cmd>
		</exporter>
		<exporter>
			<condition>
				<reference>#EXTENSION#</reference>
				<pattern>mp4|flv</pattern>
			</condition>
			<name>del</name>
			<output>Deleting</output>
			<cmd>cmd /c del D:\divx\regular\#TVSHOW_NAME#_#EPISODE_NAME_CUT#.#EXTENSION#</cmd>
		</exporter>
	</exporter>
	-->
	<allDownloadTimeout>3600</allDownloadTimeout>
	<exportTimeout>3600</exportTimeout>
	<simultaneousTaskNumber>
		<taskName>export</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>export_main</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>search</taskName>
		<size>5</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>download</taskName>
		<size>2</size>
	</simultaneousTaskNumber>
	<simultaneousTaskNumber>
		<taskName>curl</taskName>
		<size>2</size>
	</simultaneousTaskNumber>	
</tns:config>
